commissions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^sales/$', views.SalesListView.as_view(), name='sales'),
    url(r'^sale/(?P<pk>[0-9]+)/$', views.SaleDetailView.as_view(), name='sale-detail'),
    url(r'^sale/create/$', views.SaleCreateView.as_view(), name='sale-create'),
    url(r'^sale/(?P<pk>\d+)/update/$', views.SaleUpdateView.as_view(), name='sale-update'),
    url(r'^sale/(?P<pk>\d+)/delete/$', views.SaleDeleteView.as_view(), name='sale-delete'),
    url(r'^leases/$', views.LeaseListView.as_view(), name='leases'),
    url(r'^lease/(?P<pk>[0-9]+)/$', views.LeaseDetailView.as_view(), name='lease-detail'),
    url(r'^lease/create/$', views.LeaseCreateView.as_view(), name='lease-create'),
    url(r'^lease/(?P<pk>\d+)/update/$', views.LeaseUpdateView.as_view(), name='lease-update'),
    url(r'^lease/(?P<pk>\d+)/delete/$', views.LeaseDeleteView.as_view(), name='lease-delete'),
    url(r'^location/create/$', views.AddLocationView.as_view(), name='location-create'),
    url(r'^location/(?P<pk>[0-9]+)/$', views.LocationDetailView.as_view(), name='location-detail'),
    url(r'^locations/$', views.LocationListView.as_view(), name='locations'),

]

trec/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
]


urlpatterns += [
    url(r'^commissions/', include('commissions.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    #url(r'^$', RedirectView.as_view(url='/commissions', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

commissions/models.py
from datetime import datetime, timedelta
from django.conf import settings
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.urls import reverse
from itertools import chain
from taggit.managers import TaggableManager



from . import managers

#you can define a list of validations in a file (e.g. validators.py) and import it here, then add as an argument to the model
#from .validators import validate_content


BUSINESS_TYPE = (
    ('nc', 'Not Classified'),
    ('pizza', 'Pizza'),
    ('bank', 'Bank'),
    ('gym', 'Gym'),
    ('bagel', 'Bagels'),
    ('cafe', 'Cafe'),
    )

LEASE_WORKFLOW_STATUS = (
    ('0', 'New'),
    ('25', 'Prospect'),
    ('50', 'Signed LOI'),
    ('75', 'Signed Lease'),
    ('100', 'Closed'),
    )

SALE_WORKFLOW_STATUS = (
    ('0', 'New'),
    ('25', 'Prospect'),
    ('50', 'Signed LOI'),
    ('75', 'Signed Contract'),
    ('100', 'Closed'),
    )


class Sale(TimeStampedModel):
    """
    Model representing the sale of a property
    """
    buyer_name = models.CharField(max_length=80, blank=True)
    #***buyer_name = models.CharField(max_length=80, validators=[validate_content]) ***this will call the validate_content function above
    seller_name = models.CharField(max_length=80, blank=True)
    location_name = models.CharField(max_length=120, blank=True)
    status = models.CharField(max_length=3, choices=SALE_WORKFLOW_STATUS, blank=True, default=0, help_text="Workflow status")
    transaction_close_date = models.DateField("close date", blank=True, null=True)
    asking_price = models.DecimalField(decimal_places=2, null=False, blank=False, max_digits=20, default=0)
    contract_execution_date = models.DateField("contract signed on", blank=True, null=True)
    sellers_broker = models.CharField(max_length=80, blank=True)
    buyers_broker = models.CharField(max_length=80, blank=True)
    house_broker = models.CharField(max_length=80, blank=True)
    contingencies = models.TextField(max_length=1000, blank=True)
    closing_price = models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=20, default=0)
    deal_commission_rate = models.DecimalField(decimal_places=4, default=1.000, max_digits=5)
    house_rep_commission_split_rate = models.DecimalField(decimal_places=4, max_digits=5, default=1)
    outside_broker_commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    commission_due_date = models.DateField("commission paid on", blank=True, null=True)
    commission_payout_terms = models.TextField(max_length=1000, blank=True)
    send_invoice_to = models.CharField(max_length=120, blank=True)
    invoice_address = models.CharField(max_length=100, blank=True)
    invoice_phone = models.CharField(max_length=15, blank=True)
    invoice_city = models.CharField(max_length=30, blank=True)
    invoice_state = models.CharField(max_length=20, blank=True)
    invoice_zip = models.CharField(max_length=12, blank=True)
    contact_person = models.CharField(max_length=80, blank=True)
    outside_broker_contact = models.CharField(max_length=80, blank=True)
    outside_broker_contact_address = models.CharField(max_length=100, blank=True)
    outside_broker_contact_phone_number = models.CharField(max_length=15, blank=True)
    outside_broker_email_address = models.EmailField(blank=True)
    outside_broker_w9_on_file = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    contacts = models.ManyToManyField('Contact', blank=True)

    #added_by = models.ForeignKey(User) #this is not working as expected.  Username not pulling thru in admin

    def __str__(self):
        return self.location_name

    def get_absolute_url(self):
         """
         Returns the url to access a particular lease.
         """
         return reverse('sale-detail', args=[str(self.id)])

    @property
    def get_commissions_due_to_house(self):
        return self.deal_commission_rate * self.asking_price

    @property
    def get_commissions_due_to_house_rep(self):
        return (self.deal_commission_rate * self.asking_price ) * self.house_rep_commission_split_rate


    class Meta:
        ordering = ["location_name"]



class Lease(TimeStampedModel):
    """
    Model representing a signed lease
    """
    tenant_name = models.CharField(max_length=80, blank=True)
    property_owner_name = models.CharField(max_length=80)
    status = models.CharField(max_length=3, choices=LEASE_WORKFLOW_STATUS, blank=True, default=0, help_text="Workflow status")
    location_name = models.CharField(max_length=120)
    lease_term_in_months = models.IntegerField("lease term", null=True, blank=True)
    size_of_space = models.IntegerField(null=True, blank=True, default=0)
    rent_price = models.DecimalField(decimal_places=2, max_digits=8, default=0)
    lease_execution_date = models.DateField(null=True, blank=True)
    contingency_period_in_days = models.IntegerField("contingency period", default=0)
    contingency_start_date = models.DateField(null=True, blank=True)
    rent_commencement_date = models.DateField(null=True, blank=True)
    rent_rate_factor = models.DecimalField(decimal_places=4, default=1, max_digits=5)
    occupancy_date = models.DateField(null=True, blank=True)
    landlord_broker = models.CharField(max_length=80, blank=True)
    tenant_broker = models.CharField(max_length=80, blank=True)
    lease_expiration_date = models.DateField(null=True, blank=True)
    contingencies = models.TextField(max_length=1000, blank=True)
    deal_commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    house_broker = models.CharField(max_length=80, blank=True)
    house_broker_commission_rate = models.DecimalField(decimal_places=4, null=True, blank=True, max_digits=5, default=0)
    outside_broker_commission_rate = models.DecimalField(decimal_places=4, null=True, blank=True, max_digits=5, default=0)
    commission_payout_terms = models.TextField(max_length=1000, blank=True)
    '''need to refactor the invoice section'''
    send_invoice_to = models.CharField(max_length=120, blank=True)
    invoice_address = models.CharField(max_length=100, blank=True)
    invoice_city = models.CharField(max_length=30, blank=True)
    invoice_state = models.CharField(max_length=20, blank=True)
    invoice_zip = models.CharField(max_length=12, blank=True)
    invoice_phone = models.CharField(max_length=15, blank=True)
    contact_person = models.CharField(max_length=80, blank=True)
    '''need to refactor the brokers sections'''
    outside_broker_contact = models.CharField(max_length=80, blank=True)
    outside_broker_contact_address = models.CharField(max_length=100, blank=True)
    outside_broker_contact_phone_number = models.CharField(max_length=15, blank=True)
    outside_broker_email_address = models.EmailField(blank=True)
    outside_broker_w9_on_file = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    #added_by = models.ForeignKey(MyUser, blank=True, null=True)

    def __str__(self):
        return self.location_name

    def get_absolute_url(self):
         """
         Returns the url to access a particular lease.
         """
         return reverse('lease-detail', args=[str(self.id)])


    @property
    def get_aggregate_lease_commission(self):
        return float(self.size_of_space) * float(self.rent_price) * float((self.lease_term_in_months/12)) * float(self.deal_commission_rate) * float(self.rent_rate_factor)

    @property
    def contingency_end_date(self):
        return self.contingency_start_date + timedelta(days=self.contingency_period_in_days)



    '''
    this code is not working
    @property
    def display_option(self):
        """
        creates a string for the lease option.  this is required to see the lease option in the admin (since its a many to many join)
        """
        return ', '.join([ option.start_date for option in self.option.all()[:25] ])
    #display_option.option_commencement_date = 'Option Start Date'
    '''
    class Meta:
        ordering = ("-created",)

class Term(TimeStampedModel):
    """
    Model representing terms on a lease
    """
    lease = models.ForeignKey('Lease', on_delete=models.CASCADE, null=True)
    sale = models.ForeignKey('Sale', on_delete=models.CASCADE, null=True)
    terms = models.TextField(blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)

    def __str__(self):
        return '%s - %s' % (self.start_date, self.end_date)

    class Meta:
        ordering = ['created']

    @property
    def get_lease_term_commission(self):
        return float(self.lease.size_of_space) * float(self.lease.rent_price) * float(self.commission_rate) * float(self.lease.rent_rate_factor)

    @property
    def get_sale_gross_commission(self):
        return float(self.sale.closing_price) * float(self.sale.deal_commission_rate)


class Option(models.Model):
    """
    Model representing options on a lease
    """
    lease = models.ForeignKey('Lease', on_delete=models.CASCADE, null=True)
    terms = models.TextField(blank=True)
    notice_date = models.DateField(null=True, blank=True)
    commencement_date = models.DateField(null=True, blank=True)
    expiration_date = models.DateField(null=True, blank=True)
    size = models.IntegerField(null=True, blank=True, default=0)
    commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    contingencies = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '%s - %s - %s' % (self.lease, self.commencement_date, self.expiration_date)

    class Meta:
        ordering = ("-expiration_date",)


class Location(TimeStampedModel):

commissions/views.py
import datetime
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin #TODO
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms import modelformset_factory
from django.forms.utils import ErrorList
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from itertools import chain
from operator import attrgetter


from .forms import AddSaleForm, AddLeaseForm, AddLocationForm

from .models import Sale, Lease, Term, Option, Location, Tenant

'''
def lease_formset_view(request):
    LeaseModelFormset = modelformset_factory(Lease, fields=['location_name',
                                                            'term_start_date'],
                                                            extra=2)
    formset = LeaseModelFormset(request.POST or None)
    if formset.is_valid():
        for form in formset:
            print(form.cleaned_data)
    context = {
        "formset": formset
    }
    return render(request, "lease_formset_view.html", context)
'''

#Views for sales
class SalesListView(generic.ListView):
    model = Sale

    def get_context_data(self, *args, **kwargs):
        context = super(SalesListView, self).get_context_data(*args, **kwargs)

class SaleDetailView(generic.DetailView):
    model = Sale

class SaleCreateView(CreateView):
    model = Sale
    fields = '__all__'

class SaleUpdateView(UpdateView):
    model = Sale
    fields = '__all__'

class SaleDeleteView(DeleteView):
    model = Sale
    success_url = reverse_lazy('sales')
#End views for sales


#Views for leases
class LeaseListView(generic.ListView):
    model = Lease

class LeaseDetailView(generic.DetailView):
    model = Lease

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(LeaseDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['options_list'] = Option.objects.all()
        return context


class LeaseCreateView(CreateView):
    model = Lease
    fields = '__all__'

class LeaseUpdateView(UpdateView):
    model = Lease
    fields = '__all__'

class LeaseDeleteView(DeleteView):
    model = Lease
    success_url = reverse_lazy('leases')
#End views for leases


#Views for Locations and tenants
class LocationListView(generic.ListView):
    model = Location

class LocationDetailView(generic.DetailView):
    model = Location

class AddLocationView(CreateView):
    model = Location
    fields = '__all__'



class DashboardView(generic.ListView):
    template_name  = 'index.html'
    queryset = Lease.objects.all() #OR Sale.objects.all()

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['leases'] = Lease.objects.all()
        context['sales'] = Sale.objects.all()
        return context

class MarketingPageView(generic.TemplateView):
    template_name  = 'home.html'


def index(request):
    """
    function based view  for the home page of this site
    """
    recent_closed_leases=Lease.objects.all()[:5]
    recent_closed_sales=Sale.objects.all()[:5]

    #Generate counts for some main objects
#    num_deals=Deal.objects.all().count()
    num_leases=Lease.objects.all().count()
    num_sales=Sale.objects.all().count()
#    num_options=Option.objects.all().count()
#    num_contacts=Contacts.objects.all().count()
    # Available books (status = 'a')
    #num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    #num_authors=Author.objects.count() #'All' is implied by default

    #Render the html template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={
            'recent_closed_leases':recent_closed_leases,
            'recent_closed_sales':recent_closed_sales,
            'num_sales':num_sales,
            'num_leases':num_leases,
        },
    )

commissions/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container">
   <div class="dashhead">
     <div class="dashhead-titles">
       <h6 class="dashhead-subtitle">Index</h6>
       <h3 class="dashhead-title">Overview</h3>
     </div>

     <div class="dashhead-toolbar">
       <div class="input-with-icon dashhead-toolbar-item">
         <input type="text" value="01/01/15 - 01/08/15" class="form-control" data-provide="datepicker">
         <span class="icon icon-calendar"></span>
       </div>
       <span class="dashhead-toolbar-divider hidden-sm-down"></span>
       <div class="btn-group dashhead-toolbar-item btn-group-thirds">
         <button type="button" class="btn btn-outline-primary">Day</button>
         <button type="button" class="btn btn-outline-primary active">Week</button>
         <button type="button" class="btn btn-outline-primary">Month</button>
       </div>
     </div>
   </div>

   <ul class="nav nav-bordered mt-4 mt-md-2 mb-0 clearfix" role="tablist">
     <li class="nav-item" role="presentation">
       <a href="#traffic" class="nav-link active" role="tab" data-toggle="tab" aria-controls="traffic">Traffic</a>
     </li>
     <li class="nav-item" role="presentation">
       <a href="#sales" class="nav-link" role="tab" data-toggle="tab" aria-controls="sales">Sales</a>
     </li>
     <li class="nav-item" role="presentation">
       <a href="#support" class="nav-link" role="tab" data-toggle="tab" aria-controls="support">Support</a>
     </li>
   </ul>

   <hr class="mt-0 mb-5">

   <div class="tab-content">
     <div role="tabpanel" class="tab-pane active" id="traffic">
       <div class="row text-center m-t-md">
         <div class="col-md-4 mb-5">
           <div class="w-3 mx-auto">
             <canvas
               class="ex-graph"
               width="200" height="200"
               data-chart="doughnut"
               data-dataset="[{{ num_leases}}, {{ num_sales}} ]"
               data-dataset-options="{ backgroundColor: ['#1ca8dd', '#1bc98e'] }"
               data-labels="['Leases', 'Sales']">
             </canvas>
           </div>
           <strong class="text-muted">Deal Types</strong>
           <h4>Sales vs Leases</h4>
         </div>
         <div class="col-md-4 mb-4">
           <div class="w-3 mx-auto">
             <canvas
               class="ex-graph"
               width="200" height="200"
               data-chart="doughnut"
               data-dataset="[330, 30]"
               data-dataset-options="{ backgroundColor: ['#1ca8dd', '#1bc98e'] }"
               data-labels="['Returning', 'New']"
               >
             </canvas>
           </div>
           <strong class="text-muted">Revenue</strong>
           <h4>Lorem vs Ipsum</h4>
         </div>
         <div class="col-md-4 mb-5">
           <div class="w-3 mx-auto">
             <canvas
               class="ex-graph"
               width="200" height="200"
               data-chart="doughnut"
               data-dataset="[100, 260]"
               data-dataset-options="{ backgroundColor: ['#1ca8dd', '#1bc98e'] }"
               data-labels="['Referrals', 'Direct']"
               >
             </canvas>
           </div>
           <strong class="text-muted">Traffic</strong>
           <h4>Ipsum vs Dolar Sit</h4>
         </div>
       </div>
     </div>

     <div role="tabpanel" class="tab-pane" id="sales">
       <div class="ex-line-graphs mb-5">
         <canvas
           class="ex-line-graph"
           width="600" height="400"
           data-chart="line"
           data-dataset="[[2500, 3300, 2512, 2775, 2498, 3512, 2925, 4275, 3507, 3825, 3445, 3985]]"
           data-labels="['','Aug 29','','','Sept 5','','','Sept 12','','','Sept 19','']">
         </canvas>
       </div>
     </div>

     <div role="tabpanel" class="tab-pane" id="support">
       <div class="ex-line-graphs mb-5">
         <canvas
           class="ex-line-graph"
           width="600" height="400"
           data-chart="bar"
           data-labels="['August','September','October','November','December','January','February']"
           data-dataset="[[65, 59, 80, 81, 56, 55, 40], [28, 48, 40, 19, 86, 27, 90]]"
           data-dataset-options="[{label: 'First dataset'}, {label: 'Second dataset'}]">
         </canvas>
       </div>
     </div>
   </div>

   <div class="hr-divider my-4">
     <h3 class="hr-divider-content hr-divider-heading">Quick stats</h3>
   </div>

   <div class="row statcards mt-3 mb-3 text-xs-center text-md-left">
     <div class="col-6 col-md-3 statcard mb-4">
       <h3 class="statcard-number text-success">
         12,938
         <small class="delta-indicator delta-positive">5%</small>
       </h3>
       <span class="statcard-desc">Page views</span>
     </div>
     <div class="col-6 col-md-3 statcard mb-4">
       <h3 class="statcard-number text-danger">
         758
         <small class="delta-indicator delta-negative">1.3%</small>
       </h3>
       <span class="statcard-desc">Downloads</span>
     </div>
     <div class="col-6 col-md-3 statcard mb-4">
       <h3 class="statcard-number text-success">
         1,293
         <small class="delta-indicator delta-positive">6.75%</small>
       </h3>
       <span class="statcard-desc">Sign-ups</span>
     </div>
     <div class="col-6 col-md-3 statcard mb-4">
       <h3 class="statcard-number text-danger">
         758
         <small class="delta-indicator delta-negative">1.3%</small>
       </h3>
       <span class="statcard-desc">Downloads</span>
     </div>
   </div>

   <hr class="my-4">


   <div class="row">

     <div class="col-lg-4 mb-5">

       <div class="list-group mb-3">
         <h6 class="list-group-header">
           Sales
         </h6>
         {% if recent_closed_sales %}
         {% for sale in recent_closed_sales %}

           <a class="list-group-item list-group-item-action" href="href="{{ sale.get_absolute_url }}">
             <span class="list-group-progress" style="width: 62.4%;"></span>
             <span class="float-right text-muted">62.4%</span>
             {{ sale.location_name }}
           </a>

          {% endfor %}
          {% else %}
          <a class="list-group-item list-group-item-action" href="{% url 'sale-create' %}">
            <span class="float-right text-muted"></span>
            No sales.  Click to add a new sale.
          </a>

{% endif %}

       </div>
       <a href="{% url 'sales' %}" class="btn btn-outline-primary px-3">All sales</a>
     </div>
     <div class="col-lg-4 mb-5">
       <div class="list-group mb-3">
         <h6 class="list-group-header">
           Leases
         </h6>
         {% if recent_closed_leases %}
         {% for lease in recent_closed_leases %}

           <a class="list-group-item list-group-item-action" href="{{ lease.get_absolute_url }}">
             <span class="float-right text-muted">{{ get_aggregate_lease_commission }}</span>
             {{ lease.tenant_name }}
           </a>
          {% endfor %}
           {% else %}
           <a class="list-group-item list-group-item-action" href="{% url 'lease-create' %}">
             <span class="float-right text-muted"></span>
             No leases.  Click to add a new lease.
           </a>

           {% endif %}


       </div>

       <a href="{% url 'leases' %}" class="btn btn-outline-primary px-3">All leases</a>
     </div>
     <div class="col-lg-4 mb-5">
       <div class="list-group mb-3">
         <h6 class="list-group-header">
           Tenant Reps
         </h6>
         {% if sale_list %}
         {% for sale in sale_list %}

           <a class="list-group-item list-group-item-action" href="href="{{ sale.get_absolute_url }}">
             <span class="list-group-progress" style="width: 62.4%;"></span>
             <span class="float-right text-muted">62.4%</span>
             {{ sale.location_name }}
           </a>

          {% endfor %}
          {% else %}
          <a class="list-group-item list-group-item-action" href="{% url 'sale-create' %}">
            <span class="float-right text-muted"></span>
            Not yet implemented.  Need to add model
          </a>

{% endif %}


       </div>
       <a href="#" class="btn btn-outline-primary px-3">Not implemented</a>
     </div>
   </div>




 </div>
 </div>
{% endblock %}

commissions/templates/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message }}
  </div>
{% endfor %}

commissions/templates/paginator.html
<div class="text-center">
  <nav>
    <ul class="pagination">
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Previous">
          <span aria-hidden="true">&laquo;</span>
          <span class="sr-only">Previous</span>
        </a>
      </li>
      <li class="page-item active"><a class="page-link" href="#">1</a></li>
      <li class="page-item"><a class="page-link" href="#">2</a></li>
      <li class="page-item"><a class="page-link" href="#">3</a></li>
      <li class="page-item"><a class="page-link" href="#">4</a></li>
      <li class="page-item"><a class="page-link" href="#">5</a></li>
      <li class="page-item">
        <a class="page-link" href="#" aria-label="Next">
          <span aria-hidden="true">&raquo;</span>
          <span class="sr-only">Next</span>
        </a>
      </li>
    </ul>
  </nav>
</div>