commissions/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^dashboard/$', views.DashboardView.as_view(), name='dashboard'),
    url(r'^sales/$', views.SalesListView.as_view(), name='sales'),
    url(r'^sale/(?P<pk>[0-9]+)/$', views.SaleDetailView.as_view(), name='sale-detail'),
    url(r'^sale/create/$', views.SaleCreateView.as_view(), name='sale-create'),
    url(r'^sale/(?P<pk>\d+)/update/$', views.SaleUpdateView.as_view(), name='sale-update'),
    url(r'^sale/(?P<pk>\d+)/delete/$', views.SaleDeleteView.as_view(), name='sale-delete'),
    url(r'^leases/$', views.LeaseListView.as_view(), name='leases'),
    url(r'^lease/(?P<pk>[0-9]+)/$', views.LeaseDetailView.as_view(), name='lease-detail'),
    url(r'^lease/create/$', views.LeaseCreateView.as_view(), name='lease-create'),
    url(r'^lease/(?P<pk>\d+)/update/$', views.LeaseUpdateView.as_view(), name='lease-update'),
    url(r'^lease/(?P<pk>\d+)/delete/$', views.LeaseDeleteView.as_view(), name='lease-delete'),
    url(r'^location/create/$', views.AddLocationView.as_view(), name='location-create'),
    url(r'^location/(?P<pk>[0-9]+)/$', views.LocationDetailView.as_view(), name='location-detail'),
    url(r'^locations/$', views.LocationListView.as_view(), name='locations'),

]

trec/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import RedirectView, TemplateView


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('registration.backends.default.urls')),
]


urlpatterns += [
    url(r'^commissions/', include('commissions.urls')),
    url(r'^$', TemplateView.as_view(template_name='home.html')),
    #url(r'^$', RedirectView.as_view(url='/commissions', permanent=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

commissions/models.py
from datetime import datetime, timedelta
from django.conf import settings
from django.db import models
from django_extensions.db.models import TimeStampedModel
from django.urls import reverse
from itertools import chain
from taggit.managers import TaggableManager



from . import managers

#you can define a list of validations in a file (e.g. validators.py) and import it here, then add as an argument to the model
#from .validators import validate_content


BUSINESS_TYPE = (
    ('nc', 'Not Classified'),
    ('pizza', 'Pizza'),
    ('bank', 'Bank'),
    ('gym', 'Gym'),
    ('bagel', 'Bagels'),
    ('cafe', 'Cafe'),
    )

LEASE_WORKFLOW_STATUS = (
    ('0', 'New'),
    ('25', 'Prospect'),
    ('50', 'Signed LOI'),
    ('75', 'Signed Lease'),
    ('100', 'Closed'),
    )

SALE_WORKFLOW_STATUS = (
    ('0', 'New'),
    ('25', 'Prospect'),
    ('50', 'Signed LOI'),
    ('75', 'Signed Contract'),
    ('100', 'Closed'),
    )


class Sale(TimeStampedModel):
    """
    Model representing the sale of a property
    """
    buyer_name = models.CharField(max_length=80, blank=True)
    #***buyer_name = models.CharField(max_length=80, validators=[validate_content]) ***this will call the validate_content function above
    seller_name = models.CharField(max_length=80, blank=True)
    location_name = models.CharField(max_length=120, blank=True)
    status = models.CharField(max_length=3, choices=SALE_WORKFLOW_STATUS, blank=True, default=0, help_text="Workflow status")
    transaction_close_date = models.DateField("close date", blank=True, null=True)
    asking_price = models.DecimalField(decimal_places=2, null=False, blank=False, max_digits=20, default=0)
    contract_execution_date = models.DateField("contract signed on", blank=True, null=True)
    sellers_broker = models.CharField(max_length=80, blank=True)
    buyers_broker = models.CharField(max_length=80, blank=True)
    house_broker = models.CharField(max_length=80, blank=True)
    contingencies = models.TextField(max_length=1000, blank=True)
    closing_price = models.DecimalField(decimal_places=2, null=True, blank=True, max_digits=20, default=0)
    deal_commission_rate = models.DecimalField(decimal_places=4, default=1.000, max_digits=5)
    house_rep_commission_split_rate = models.DecimalField(decimal_places=4, max_digits=5, default=1)
    outside_broker_commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    commission_due_date = models.DateField("commission paid on", blank=True, null=True)
    commission_payout_terms = models.TextField(max_length=1000, blank=True)
    send_invoice_to = models.CharField(max_length=120, blank=True)
    invoice_address = models.CharField(max_length=100, blank=True)
    invoice_phone = models.CharField(max_length=15, blank=True)
    invoice_city = models.CharField(max_length=30, blank=True)
    invoice_state = models.CharField(max_length=20, blank=True)
    invoice_zip = models.CharField(max_length=12, blank=True)
    contact_person = models.CharField(max_length=80, blank=True)
    outside_broker_contact = models.CharField(max_length=80, blank=True)
    outside_broker_contact_address = models.CharField(max_length=100, blank=True)
    outside_broker_contact_phone_number = models.CharField(max_length=15, blank=True)
    outside_broker_email_address = models.EmailField(blank=True)
    outside_broker_w9_on_file = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    contacts = models.ManyToManyField('Contact', blank=True)

    #added_by = models.ForeignKey(User) #this is not working as expected.  Username not pulling thru in admin

    def __str__(self):
        return self.location_name

    def get_absolute_url(self):
         """
         Returns the url to access a particular lease.
         """
         return reverse('sale-detail', args=[str(self.id)])

    @property
    def get_commissions_due_to_house(self):
        return self.deal_commission_rate * self.asking_price

    @property
    def get_commissions_due_to_house_rep(self):
        return (self.deal_commission_rate * self.asking_price ) * self.house_rep_commission_split_rate


    class Meta:
        ordering = ["location_name"]



class Lease(TimeStampedModel):
    """
    Model representing a signed lease
    """
    tenant_name = models.CharField(max_length=80, blank=True)
    property_owner_name = models.CharField(max_length=80)
    status = models.CharField(max_length=3, choices=LEASE_WORKFLOW_STATUS, blank=True, default=0, help_text="Workflow status")
    location_name = models.CharField(max_length=120)
    lease_term_in_months = models.IntegerField("lease term", null=True, blank=True)
    size_of_space = models.IntegerField(null=True, blank=True, default=0)
    rent_price = models.DecimalField(decimal_places=2, max_digits=8, default=0)
    lease_execution_date = models.DateField(null=True, blank=True)
    contingency_period_in_days = models.IntegerField("contingency period", default=0)
    contingency_start_date = models.DateField(null=True, blank=True)
    rent_commencement_date = models.DateField(null=True, blank=True)
    rent_rate_factor = models.DecimalField(decimal_places=4, default=1, max_digits=5)
    occupancy_date = models.DateField(null=True, blank=True)
    landlord_broker = models.CharField(max_length=80, blank=True)
    tenant_broker = models.CharField(max_length=80, blank=True)
    lease_expiration_date = models.DateField(null=True, blank=True)
    contingencies = models.TextField(max_length=1000, blank=True)
    deal_commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    house_broker = models.CharField(max_length=80, blank=True)
    house_broker_commission_rate = models.DecimalField(decimal_places=4, null=True, blank=True, max_digits=5, default=0)
    outside_broker_commission_rate = models.DecimalField(decimal_places=4, null=True, blank=True, max_digits=5, default=0)
    commission_payout_terms = models.TextField(max_length=1000, blank=True)
    '''need to refactor the invoice section'''
    send_invoice_to = models.CharField(max_length=120, blank=True)
    invoice_address = models.CharField(max_length=100, blank=True)
    invoice_city = models.CharField(max_length=30, blank=True)
    invoice_state = models.CharField(max_length=20, blank=True)
    invoice_zip = models.CharField(max_length=12, blank=True)
    invoice_phone = models.CharField(max_length=15, blank=True)
    contact_person = models.CharField(max_length=80, blank=True)
    '''need to refactor the brokers sections'''
    outside_broker_contact = models.CharField(max_length=80, blank=True)
    outside_broker_contact_address = models.CharField(max_length=100, blank=True)
    outside_broker_contact_phone_number = models.CharField(max_length=15, blank=True)
    outside_broker_email_address = models.EmailField(blank=True)
    outside_broker_w9_on_file = models.BooleanField(default=False)
    notes = models.TextField(blank=True)
    #added_by = models.ForeignKey(MyUser, blank=True, null=True)

    def __str__(self):
        return self.location_name

    def get_absolute_url(self):
         """
         Returns the url to access a particular lease.
         """
         return reverse('lease-detail', args=[str(self.id)])


    @property
    def get_aggregate_lease_commission(self):
        return float(self.size_of_space) * float(self.rent_price) * float((self.lease_term_in_months/12)) * float(self.deal_commission_rate) * float(self.rent_rate_factor)

    @property
    def contingency_end_date(self):
        return self.contingency_start_date + timedelta(days=self.contingency_period_in_days)



    '''
    this code is not working
    @property
    def display_option(self):
        """
        creates a string for the lease option.  this is required to see the lease option in the admin (since its a many to many join)
        """
        return ', '.join([ option.start_date for option in self.option.all()[:25] ])
    #display_option.option_commencement_date = 'Option Start Date'
    '''
    class Meta:
        ordering = ("-created",)

class Term(TimeStampedModel):
    """
    Model representing terms on a lease
    """
    lease = models.ForeignKey('Lease', on_delete=models.CASCADE, null=True)
    sale = models.ForeignKey('Sale', on_delete=models.CASCADE, null=True)
    terms = models.TextField(blank=True)
    start_date = models.DateField(null=True, blank=True)
    end_date = models.DateField(null=True, blank=True)
    commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)

    def __str__(self):
        return '%s - %s' % (self.start_date, self.end_date)

    class Meta:
        ordering = ['created']

    @property
    def get_lease_term_commission(self):
        return float(self.lease.size_of_space) * float(self.lease.rent_price) * float(self.commission_rate) * float(self.lease.rent_rate_factor)

    @property
    def get_sale_gross_commission(self):
        return float(self.sale.closing_price) * float(self.sale.deal_commission_rate)


class Option(models.Model):
    """
    Model representing options on a lease
    """
    lease = models.ForeignKey('Lease', on_delete=models.CASCADE, null=True)
    terms = models.TextField(blank=True)
    notice_date = models.DateField(null=True, blank=True)
    commencement_date = models.DateField(null=True, blank=True)
    expiration_date = models.DateField(null=True, blank=True)
    size = models.IntegerField(null=True, blank=True, default=0)
    commission_rate = models.DecimalField(decimal_places=4, default=0, max_digits=5)
    contingencies = models.TextField(blank=True)
    created = models.DateTimeField(auto_now=False, auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True, auto_now_add=False)

    def __str__(self):
        return '%s - %s - %s' % (self.lease, self.commencement_date, self.expiration_date)

    class Meta:
        ordering = ("-expiration_date",)


class Location(TimeStampedModel):

commissions/views.py
import datetime
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin #TODO
from django.core.urlresolvers import reverse
from django.db.models import Q
from django.forms import modelformset_factory
from django.forms.utils import ErrorList
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from itertools import chain
from operator import attrgetter


from .forms import AddSaleForm, AddLeaseForm, AddLocationForm

from .models import Sale, Lease, Term, Option, Location, Tenant

'''
def lease_formset_view(request):
    LeaseModelFormset = modelformset_factory(Lease, fields=['location_name',
                                                            'term_start_date'],
                                                            extra=2)
    formset = LeaseModelFormset(request.POST or None)
    if formset.is_valid():
        for form in formset:
            print(form.cleaned_data)
    context = {
        "formset": formset
    }
    return render(request, "lease_formset_view.html", context)
'''

#Views for sales
class SalesListView(generic.ListView):
    model = Sale

    def get_context_data(self, *args, **kwargs):
        context = super(SalesListView, self).get_context_data(*args, **kwargs)

class SaleDetailView(generic.DetailView):
    model = Sale

class SaleCreateView(CreateView):
    model = Sale
    fields = '__all__'

class SaleUpdateView(UpdateView):
    model = Sale
    fields = '__all__'

class SaleDeleteView(DeleteView):
    model = Sale
    success_url = reverse_lazy('sales')
#End views for sales


#Views for leases
class LeaseListView(generic.ListView):
    model = Lease

class LeaseDetailView(generic.DetailView):
    model = Lease

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(LeaseDetailView, self).get_context_data(**kwargs)
        # Add in a QuerySet of all the books
        context['options_list'] = Option.objects.all()
        return context


class LeaseCreateView(CreateView):
    model = Lease
    fields = '__all__'

class LeaseUpdateView(UpdateView):
    model = Lease
    fields = '__all__'

class LeaseDeleteView(DeleteView):
    model = Lease
    success_url = reverse_lazy('leases')
#End views for leases


#Views for Locations and tenants
class LocationListView(generic.ListView):
    model = Location

class LocationDetailView(generic.DetailView):
    model = Location

class AddLocationView(CreateView):
    model = Location
    fields = '__all__'



class DashboardView(generic.ListView):
    template_name  = 'index.html'
    queryset = Lease.objects.all() #OR Sale.objects.all()

    def get_context_data(self, **kwargs):
        context = super(DashboardView, self).get_context_data(**kwargs)
        context['leases'] = Lease.objects.all()
        context['sales'] = Sale.objects.all()
        return context

class MarketingPageView(generic.TemplateView):
    template_name  = 'home.html'


def index(request):
    """
    function based view  for the home page of this site
    """
    recent_closed_leases=Lease.objects.all()[:5]
    recent_closed_sales=Sale.objects.all()[:5]

    #Generate counts for some main objects
#    num_deals=Deal.objects.all().count()
    num_leases=Lease.objects.all().count()
    num_sales=Sale.objects.all().count()
#    num_options=Option.objects.all().count()
#    num_contacts=Contacts.objects.all().count()
    # Available books (status = 'a')
    #num_instances_available=BookInstance.objects.filter(status__exact='a').count()
    #num_authors=Author.objects.count() #'All' is implied by default

    #Render the html template index.html with the data in the context variable
    return render(
        request,
        'index.html',
        context={
            'recent_closed_leases':recent_closed_leases,
            'recent_closed_sales':recent_closed_sales,
            'num_sales':num_sales,
            'num_leases':num_leases,
        },
    )

commissions/templates/commissions/lease_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Lease</h1>

<p>Are you sure you want to delete this lease? {{ lease }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

commissions/templates/commissions/lease_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="dashhead mt-4">

<div class="dashhead-titles">
  <h6 class="dashhead-subtitle">Lease Detail</h6>
  <h2 class="dashhead-title">{{ lease.location_name }}</h2>
</div>


<div class="flextable table-actions">
  <div class="flextable-item flextable-primary">

  </div>
  <div class="flextable-item">
    <div class="btn-group">
      <button type="button" class="btn btn-outline-primary" href="#">
        <span class="icon icon-pencil"></span>
      </button>
      <button type="button" class="btn btn-outline-primary" href="#">
        <span class="icon icon-erase"></span>
      </button>
    </div>
  </div>
</div>
</div>



<!--<div class="hr-divider mt-5 mb-4">
  <h3 class="hr-divider-content hr-divider-heading">Lease Details</h3>
</div>
-->
<ul>
  <li><strong>Property owner:</strong> {{ lease.property_owner_name }}
  <li><strong>Tenant:</strong> {{ lease.tenant_name }}
  <li><strong>Asking price:</strong> {{ lease.rent_price }}
  <li><strong>Size of space:</strong> {{ lease.size_of_space }}
  <li><strong>Lease term:</strong> {{ lease.lease_term_in_months }}</li>
  <li><strong>size_of_space:</strong> {{ lease.size_of_space }}</li>
  <li><strong>rent_price:</strong> {{ lease.rent_price }}</li>
  <li><strong>deal_commission_rate:</strong> {{ lease.deal_commission_rate }}</li>
  <li><strong>aggregate_lease_commission:</strong> {{ lease.get_aggregate_lease_commission }}</li>
  <li><strong>house_broker_commission_rate:</strong> {{ lease.house_broker_commission_rate }}</li>
  <li><strong>outside_broker_commission_rate:</strong> {{ lease.outside_broker_commission_rate }}</li>
  <li><strong>commission_payout_terms:</strong> {{ lease.commission_payout_terms }}</li>
  <li><strong>Status:</strong> {{ lease.status }}</li>
  <li><strong>permit_type:</strong> {{ lease.permit_type }}</li>
  <li><strong>notes:</strong> {{ lease.notes }}</li>
  <li><strong>added_by:</strong> {{ lease.added_by }}</li>

  <li><strong>contingency_period_in_days </strong> {{ lease.contingency_period_in_days }}</li>
  <li><strong>Contingency end date: </strong> {{ lease.contingency_end_date }}</li>






  <li><strong>contingencies:</strong> {{ lease.contingencies }}</li>
                        <li>{{ lease.contingency_time_in_days }}</li>
  <li><strong>added_by:</strong> {{ lease.added_by }}</li>

    <hr>
    <strong>Dates</strong>
    <li><strong>Signed Lease Date:</strong> {{ lease.signed_lease_date }}</li>
    <li><strong>lease_execution_date:</strong> {{ lease.lease_execution_date }}</li>
    <li><strong>lease_expiration_date:</strong> {{ lease.lease_expiration_date }}</li>
    <li><strong>contingency_start_date:</strong> {{ lease.contingency_start_date }}</li>

    <li><strong>rent_commencement_date:</strong> {{ lease.rent_commencement_date }}</li>
    <li><strong>occupancy_date:</strong> {{ lease.occupancy_date }}</li>
    <br/>
    <hr>

    <strong>Terms</strong>
    <li><strong>landlord_broker:</strong> {{ lease.landlord_broker }}</li>
    <li><strong>tenant_broker:</strong> {{ lease.tenant_broker }}</li>
    <li><strong>house_broker:</strong> {{ lease.house_broker }}</li>
    <li><strong>contingency_start_date:</strong> {{ lease.contingency_start_date }}</li>

    <li><strong>rent_commencement_date:</strong> {{ lease.rent_commencement_date }}</li>



    <br/>
    <hr>
    <strong>Brokers</strong>
    <li><strong>landlord_broker:</strong> {{ lease.landlord_broker }}</li>
    <li><strong>tenant_broker:</strong> {{ lease.tenant_broker }}</li>
    <li><strong>house_broker:</strong> {{ lease.house_broker }}</li>
    <li><strong>contingency_start_date:</strong> {{ lease.contingency_start_date }}</li>

    <li><strong>rent_commencement_date:</strong> {{ lease.rent_commencement_date }}</li>
    <br/>
    <hr>
    <strong>Outside Brokers</strong>
    <li><strong>outside_broker_contact:</strong> {{ lease.outside_broker_contact }}</li>
    <li><strong>outside_broker_contact_address:</strong> {{ lease.outside_broker_contact_address }}</li>
    <li><strong>outside_broker_contact_phone_number:</strong> {{ lease.outside_broker_contact_phone_number }}</li>
    <li><strong>outside_broker_email_address:</strong> {{ lease.outside_broker_email_address }}</li>
    <li><strong>outside_broker_w9_on_file:</strong> {{ lease.outside_broker_w9_on_file }}</li>
    <br/>
    <hr>
    <strong>Invoice</strong>
    <li><strong>send_invoice_to:</strong> {{ lease.send_invoice_to }}</li>
    <li><strong>contact_person:</strong> {{ lease.contact_person }}</li>
    <li><strong>invoice_address:</strong> {{ lease.invoice_address }}</li>
    <li><strong>invoice_city:</strong> {{ lease.invoice_city }}</li>
    <li><strong>invoice_state:</strong> {{ lease.invoice_state }}</li>
    <li><strong>invoice_zip:</strong> {{ lease.invoice_zip }}</li>
    <li><strong>invoice_phone:</strong> {{ lease.invoice_phone }} </li>






    <hr>

  {% if lease.term_set %}
  <div class="hr-divider mt-5 mb-4">
    <h3 class="hr-divider-content hr-divider-heading">Lease Terms</h3>
  </div>


    <div class="container">

    <div class="table-responsive">
      <table class="table" data-sort="table">
        <thead>
          <tr>
            <!--<th><input type="checkbox" class="select-all" id="selectAll"></th>-->
            <th>Id</th>
            <th>Start Date</th>
            <th>End Date</th>
            <th>Commission (%)</th>
            <th>Term Commission</th>
          </tr>
        </thead>
        <tbody>

          {% for term in lease.term_set.all %}

          <tr>
            <!--<<td><input type="checkbox" class="select-row"></td>-->
            <td><a href="#">{{ term.id }}</a></td>
            <td>{{ term.start_date }}</td>
            <td>{{ term.end_date }}</td>
            <td>{{ term.commission_rate }}</td>
            <td>{{ term.get_lease_term_commission }}</td>
          </tr>
          {% endfor %}

        </tbody>
      </table>
    </div>
  {% else %}
  <div class="hr-divider mt-5 mb-4">
    <h3 class="hr-divider-content hr-divider-heading">No Lease Terms</h3>
  </div>



    {% endif %}






{% if lease.option_set %}
<div class="hr-divider mt-5 mb-4">
  <h3 class="hr-divider-content hr-divider-heading">Lease Options</h3>
</div>



<!--      <p class="{# if copy.status == 'a' #}text-success{# elif copy.status == 'd' #}text-danger{# else #}text-warning{# endif #}">{# copy.get_status_display #}</p>
      {# if copy.status != 'a' #}<p><strong>Due back on:</strong> {# copy.due_back #}</p> {# endif #}-->


  <div class="container">


  <div class="table-responsive">
    <table class="table" data-sort="table">
      <thead>
        <tr>
          <!--<th><input type="checkbox" class="select-all" id="selectAll"></th>-->
          <th>Id</th>
          <th>Start date</th>
          <th>End Date</th>
          <th>Rent Rate</th>
          <th>Commission</th>
        </tr>
      </thead>
      <tbody>

        {% for option in lease.option_set.all %}

        <tr>
          <!--<<td><input type="checkbox" class="select-row"></td>-->
          <td><a href="#">{{ option.id }}</a></td>
          <td>{{ option.commencement_date }}</td>
          <td>{{ option.end_date }}</td>
          <td>FIELD 2</td>
          <td>FIELD 3</td>
        </tr>
        {% endfor %}

      </tbody>
    </table>
  </div>
{% else %}
<div class="hr-divider mt-5 mb-4">
  <h3 class="hr-divider-content hr-divider-heading">No Lease Options</h3>
</div>



  {% endif %}



{% endblock %}

commissions/templates/commissions/lease_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">

<h2>Add a new lease </h2>

<form action="" method="post">
    {% csrf_token %}
    <table>
<!--original code    {{ form.as_table }} -->
    {{ form|crispy }}
    </table>
    <input type="submit" value="Submit" />

</form>
</div>
{% endblock %}

commissions/templates/commissions/location_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Location</h1>

<p>Are you sure you want to delete this location? {{ location }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

commissions/templates/commissions/location_form.html
{% extends "base.html" %}


{% block content %}
<div class="container">

<h2>Add tenant to location </h2>

<form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
      <!--{ form|crispy } -->
    </table>
    <input type="submit" value="Submit" />
</form>
</div>
{% endblock %}

commissions/templates/commissions/sale_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Sale Location</h1>

<p>Are you sure you want to delete the Location: {{ sale }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

commissions/templates/commissions/sale_detail.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
   <h1>Name of Location: {{ sale.location_name }}</h1>

   <p><strong>Seller:</strong>{{ sale.seller_name }} </p>
   <p><strong>Asking price:</strong> {{ sale.asking_price }} </p>


   {% if sale.term_set %}
   <div class="hr-divider mt-5 mb-4">
     <h3 class="hr-divider-content hr-divider-heading">Terms of Sale</h3>
   </div>


     <div class="container">

     <div class="table-responsive">
       <table class="table" data-sort="table">
         <thead>
           <tr>
             <th>Id</th>
             <th>Closing Date</th>
             <th>Commission (%)</th>
             <th>Term Commission</th>
           </tr>
         </thead>
         <tbody>

           {% for term in lease.term_set.all %}

           <tr>
             <!--<<td><input type="checkbox" class="select-row"></td>-->
             <td><a href="#">{{ term.id }}</a></td>
             <td>{{ term.end_date }}</td>
             <td>{{ term.commission_rate }}</td>
             <td>{{ term.get_term_commission }}</td>
           </tr>
           {% endfor %}

         </tbody>
       </table>
     </div>
   {% else %}
   <div class="hr-divider mt-5 mb-4">
     <h3 class="hr-divider-content hr-divider-heading">No Sale Terms</h3>
   </div>



     {% endif %}



</div>
  {% endblock %}

commissions/templates/commissions/sale_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h2> Add a new sale </h2>

<form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form|crispy }}
    </table>
    <input type="submit" value="Submit" />

</form>
</div>
{% endblock %}